ApeSwapFinance/apeswap-frontend

package.json
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/Actions/CreatePresale.tsx
src/views/Iazos/components/IazoPage/SaleStatus/SaleStatus.tsx
src/views/Iazos/hooks/useCreateIazoApi.tsx
yarn.lock

chore: Add retry to post

---

src/config/constants/apezone.ts
src/config/constants/ifo.ts
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/Actions/CreatePresale.tsx

feat: IAO contracts

---

src/views/Iazos/components/IazoPage/SaleInfo/styles.ts

chore: Fix text wrap

---

package.json
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/DateSelection/DateSelectionButton.tsx
yarn.lock

fix type error, remove invalid prop

fix react-datepicker type errors

---

src/hooks/useAllEarnings.ts

memoize contract object to prevent unbound refetching of earnings

fix unbound useEffect loop by memoizing contract object dep

---

src/state/hooks.ts

This fixes the slow first load by not setting `render` to false until we have all the data needed to properly fetch stats

add block in if_condition for stats page loading - issue 9

---

src/views/Iazos/components/IazoCard/Timer.tsx
yarn.lock

chore: Set days

---

src/views/ApeZone/components/Description/Description.tsx

feat: Updated GNANA link

---

public/images/tokens/MYRA.svg
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: Myra farm and pool

---

src/config/constants/pools.ts

feat: Added ONT pool

---

src/config/constants/pools.ts

feat: Added ONG pool

---

src/config/constants/pools.ts

feat: Refill Naut pool

---

src/config/constants/pools.ts

feat: Refill zig pool

---

src/config/constants/pools.ts

feat: Refill DEP pool

---

src/config/constants/pools.ts

DEP Pool Refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts

Moonlight Pool

---

src/config/constants/pools.ts

feat: LAND pool refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts

LAND Pool refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: SPACE pool refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts

SPACE pool

---

src/config/constants/pools.ts

feat: WATCH pool refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts

WATCH Pool refill

---

src/views/Stats/Stats.tsx

fix: Added stats warning

---

src/config/constants/pools.ts

feat: LMT pool refill

---

src/config/constants/pools.ts
src/config/constants/tokens.ts
src/views/Stats/Stats.tsx

LMT Pool Refill

---

src/config/constants/pools.ts

feat: GMR pool top up

---

src/config/constants/pools.ts

feat: Tixl pool

---

src/config/constants/pools.ts

CRYSTL Farm

---

src/hooks/useAuth.ts

fix: Updated provider message

---

src/config/constants/vaults.ts

feat: inactive crystl vaults

---

src/config/constants/vaults.ts

fix: inactive bsc vaults

---

src/views/Ifos/components/HowItWorks/HowItWorks.tsx

feat: Fixed IAO verbiage

---

src/App.tsx
src/state/hooks.ts
src/views/Farms/Farms.tsx
src/views/Home/components/CoolPools/CoolPools.tsx
src/views/Home/components/HotFarms/HotFarms.tsx
src/views/PoolFinder/index.tsx
src/views/Pools/Pools.tsx

chore: Fix find pool modal

---

src/components/SearchModal/CurrencyList.tsx
src/components/SearchModal/filtering.ts

chore: Make banana the second token

---

package.json

Updated token list

---

src/config/constants/tokens.ts
src/views/AddLiquidity/ConfirmAddModalBottom.tsx

chore: Show native symbol

---

src/views/Farms/Farms.tsx

chore: Fix farm apr sort

---

.github/ISSUE_TEMPLATE/custom.md

Add blank template

---

src/views/AddLiquidity/index.tsx

chore: Fix add liquidity

---

src/config/abi/ifoLinear.json
src/config/constants/apezone.ts
src/config/constants/ifo.ts
src/views/Ifos/components/IfoCard/ContributeInput/ContributeInput.tsx
src/views/Ifos/components/IfoCard/LinearVesting/IfoCardContribute.tsx
src/views/Ifos/hooks/useIAODeposit.ts
src/views/Ifos/hooks/useLinearIAOHarvest.ts

feat: Add test project, more tracking metrics

---

package.json
src/components/Menu/chains/bscConfig.ts
yarn.lock

chore: Add lending icon

---

package.json
src/components/Menu/chains/bscConfig.ts
yarn.lock

Lending Network

---

package.json

SYSCOIN Listing

---

src/config/constants/index.ts

chore: Frm routing

---

package.json
yarn.lock

chore: Update uikit

---

package.json
yarn.lock

chore: Uikit version

---

src/state/hooks.ts
src/views/Auction/components/AuctionCardVarients/HistoryCard.tsx
src/views/Auction/components/Price.tsx

chore: Fix prices

---

package.json

Update Listing Info - Listing BUZZ

---

src/config/constants/pools.ts

feat: MNFT Pool

---

src/App.tsx

feat: Added spinner page

---

package.json

Updated Listing Info - Listing SDAO

---

public/images/tokens/RANKER.svg
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: RANKER Farm and Pool

---

package.json
public/images/tokens/RANKER.svg
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

Updated Listing Info - RANKER Listing

---

src/config/constants/pools.ts

feat: Hotcross pool

---

src/config/constants/nfaStakingPools.ts
src/config/constants/types.ts
src/state/nfaStakingPools/fetchNfaStakingPools.ts
src/state/nfaStakingPools/index.ts
src/state/types.ts
src/views/NfaStaking/components/PoolCard/DetailsSection.tsx
src/views/NfaStaking/components/PoolCard/PoolCard.tsx

chore: Fix end time

---

public/images/tokens/FRONT.svg
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: FRONT farm and pool

---

package.json
public/images/tokens/FRONT.svg
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts
src/views/NfaStaking/NfaStaking.tsx

Updated Listing Info-Listed FRONT

---

src/config/constants/dualFarms.ts
src/config/constants/types.ts
src/state/nfaStakingPools/fetchNfaStakingPools.ts
src/views/DualFarms/DualFarms.tsx
src/views/DualFarms/components/FarmCard/CardHeading.tsx
src/views/DualFarms/components/FarmCard/DetailsSection.tsx
src/views/DualFarms/components/FarmCard/FarmCard.tsx
src/views/DualFarms/components/FarmTable/Actions/ActionPanel.tsx
src/views/DualFarms/components/FarmTable/Farm.tsx
src/views/NfaStaking/components/PoolCard/PoolCard.tsx
yarn.lock

chore: Update dual earn image

---

package.json

Update Listing Info - Delist SISTA

---

src/views/Homepage/components/WelcomeContent/WelcomeContent.tsx

feat: Update text

---

package.json

Update Listing Info - List NFTY POLYGON

---

src/views/Homepage/components/LaunchCalendar/LaunchCalendar.tsx

fix: Launch dates

---

src/views/DualFarms/components/FarmCard/CardHeading.tsx
src/views/Pools/components/PoolCard/CardHeading.tsx
src/views/Vaults/components/VaultCard/CardHeading.tsx

chore: Fix font size

---

src/views/Farms/components/DisplayFarms.tsx
src/views/Pools/components/PoolCard/CardHeading.tsx
src/views/Vaults/components/VaultCard/CardHeading.tsx

fix: Update rounding

---

package.json
yarn.lock

chore: Fix marketing modal

---

src/state/transactions/updater.tsx
src/views/Ifos/components/IfoCard/LinearVesting/index.tsx
src/views/Pools/components/PoolCard/CardActions/StakeActions.tsx

fix: 3 small fixes

---

src/config/constants/apezone.ts
src/config/constants/ifo.ts

feat: Add IAO contracts

---

src/views/Ifos/components/Ideology/Ideology.tsx

fix: Remove hashes

---

package.json

feat: ANML Listing

---

package.json

Updated Listing Info - Listed ANON

---

package.json

Updated Listing Info - Listed YOSHI

---

src/components/Menu/chains/bscConfig.ts
yarn.lock

fix: Update menu wording

---

src/components/ListViewMenu/styles.ts
src/views/Farms/components/DisplayFarms.tsx

chore: Quick tooltip fix

---

package.json

Updated Listing Info - Listing BOUNTIE

---

package.json
src/components/ListViewMenu/styles.ts
src/views/Farms/components/DisplayFarms.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/PresaleDetails/PresaleDetails.tsx

SS-IAO Minor Updates

---

src/views/Bills/components/BillsListView.tsx

fix: Available instead of buy

---

package.json

Updated Listing Info- Listed WIDI

---

src/config/constants/pools.ts

feat: DEP pool top up

---

package.json

DEP pool Top up

---

src/state/stats/getHomepageService.ts

fix: Env var for API url

---

src/components/ListViewContent/index.tsx
src/components/ListViewContent/styles.ts
src/components/ListViewContent/types.ts
src/views/Bills/components/BillsListView.tsx

fix: Bills changes

---

src/components/ListViewContent/index.tsx
src/components/ListViewContent/styles.ts
src/components/ListViewContent/types.ts
src/state/stats/getHomepageService.ts
src/views/Bills/components/BillsListView.tsx

fix: Bills enhancements

---

src/components/ListViewContent/index.tsx
src/components/ListViewContent/styles.ts
src/views/Bills/components/UserBillViews/FirstTimeCard.tsx

fix: Colors & text

---

package.json
src/components/ListView/ListCard.tsx
src/components/ListView/MobileListCard.tsx

Delisted TAPE

---

package.json

Updated Listing Info-Listed Generic Coin

---

package.json
src/components/MarketingModalContent/Bills/BillsBody1.tsx
src/components/MarketingModalContent/Bills/styles.ts
yarn.lock

Bills and Marketing Modals Bug Fixes

---

src/config/constants/bills.ts
yarn.lock

feat: Add usdc busd bill

---

package.json
src/components/ListView/ListCard.tsx
src/components/ListView/MobileListCard.tsx
src/views/Bills/components/UserBillViews/FirstTimeCard.tsx

Usdc busd bill

---

src/views/Farms/components/DisplayFarms.tsx

fix: Reverse logic on farm apu

---

src/views/Bills/components/BillsListView.tsx

fix: Bills tooltip

---

src/config/constants/bills.ts
yarn.lock

chore: Add new bill

---

src/views/Bills/components/BillsListView.tsx

chore: Add ETH-BNB Bill

---

src/config/constants/chains.ts
src/hooks/useSwapCallback.ts
src/utils/wallchainService.ts

Feat/wallchain API testing

---

src/views/Bills/components/Actions/Claim.tsx
src/views/Bills/components/Actions/ClaimAll.tsx
src/views/Bills/components/Actions/types.ts
src/views/Bills/components/Menu/index.tsx
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/UserBillViews/BillCard.tsx
src/views/Bills/components/UserBillViews/UserBillListView.tsx
src/views/Bills/components/UserBillViews/index.tsx
yarn.lock

chore: Fix bill expired

---

package.json
src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: Add Bico

---

src/views/Pools/InfoContent.tsx
src/views/Pools/components/DisplayPools.tsx
src/views/Pools/components/Menu/types.ts
yarn.lock

fix: Pools time card

---

src/views/Pools/InfoContent.tsx

fix: Hotfix pools history

---

src/views/Pools/components/Actions/HarvestAction.tsx

fix: Ape harder

---

src/views/Bills/components/BillsListView.tsx
src/views/Bills/components/Modals/BuyBillModalView.tsx
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/Modals/WarningModal.tsx
src/views/Bills/components/Modals/index.tsx
src/views/Bills/components/UserBillViews/BillCard.tsx
src/views/Bills/components/UserBillViews/FirstTimeCard.tsx
yarn.lock

chore: Add warning modal

---

src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/maticConfig.ts
src/views/Bills/components/UserBillViews/BillCard.tsx
src/views/Bills/components/UserBillViews/index.tsx

fix: Nav bar and bills

---

src/components/LiquidityWidget/ConnectButton.tsx
src/components/LiquidityWidget/CurrencyInput/NumericalInput.tsx
src/components/LiquidityWidget/CurrencyInput/index.tsx
src/components/LiquidityWidget/LiquidityInfo.tsx
src/components/LiquidityWidget/LiquidityModal.tsx
src/components/LiquidityWidget/LiquidityWidget.tsx
src/components/LiquidityWidget/index.tsx
src/components/LiquidityWidget/styles.ts
src/components/SearchModal/CurrencySearch.tsx
src/components/SearchModal/CurrencySearchModal.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Farms/components/DisplayFarms.tsx

Create widget modal and the liquidity widget to be used in it.
https://apeswap-frontend-cra.vercel.app/auction

feat: Liquidity widget

---

src/components/LiquidityWidget/CurrencyInput/index.tsx
src/components/LiquidityWidget/LiquidityWidget.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Farms/components/DisplayFarms.tsx

chore: Fix a few bugs

---

src/config/localization/translations.json

fix: Bug fix

---

package.json

Update Listing Info - Delisted TOON/GAN POLAR logo

---

src/App.tsx

fix: Farm innactive

---

src/App.tsx
yarn.lock

chore: Revert

---

src/App.tsx

fix: Swap routing

---

src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: GRVS farm and pool

---

src/config/constants/pools.ts

feat: Pools loading fix

---

src/config/constants/farms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: VTG farm and pool

---

package.json
src/config/constants/pools.ts

Updated WGICT & NFT11 Logos

---

src/components/LiquidityWidget/LiquidityModal.tsx

https://www.loom.com/share/24ac98a3310c41569b92bed82c15d6a7

chore: Allow to close add liquidity modal

---

src/config/constants/jungleFarms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: BONES jungle farm

---

package.json
src/components/Banner/index.tsx
src/components/LiquidityWidget/ConnectButton.tsx
src/components/LiquidityWidget/CurrencyInput/index.tsx
src/components/LiquidityWidget/LiquidityInfo.tsx
src/components/LiquidityWidget/LiquidityModal.tsx
src/components/LiquidityWidget/LiquidityWidget.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/Modals/WarningModal.tsx
src/views/Bills/components/Modals/index.tsx
src/views/Farms/components/DisplayFarms.tsx
src/views/JungleFarms/components/DisplayJungleFarms.tsx
src/views/Nft/components/NftCard/index.tsx
src/views/Pools/components/Actions/ApprovalAction.tsx
src/views/Pools/components/DisplayPools.tsx
src/views/Swap/components/CurrencyInputHeader.tsx
yarn.lock

Updates `uikit` package to [v1.3.2](https://github.com/ApeSwapFinance/apeswap-uikit/pull/82)  with the fixes.

chore: Update uikit package

---

package.json
src/components/LiquidityWidget/ConnectButton.tsx
src/components/LiquidityWidget/LiquidityModal.tsx
src/components/LiquidityWidget/LiquidityWidget.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/Modals/index.tsx
src/views/Farms/components/DisplayFarms.tsx
src/views/JungleFarms/components/Actions/index.tsx
src/views/JungleFarms/components/DisplayJungleFarms.tsx
src/views/Nft/components/NftCard/index.tsx
src/views/Swap/components/CurrencyInputHeader.tsx
yarn.lock

chore: Revert staging

---

src/components/LiquidityWidget/CurrencyInput/index.tsx
src/components/LiquidityWidget/LiquidityWidget.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/Modals/WarningModal.tsx
src/views/Farms/components/DisplayFarms.tsx
src/views/JungleFarms/components/DisplayJungleFarms.tsx

chore: Revert a few more changes

---

src/views/ApeZone/Zone.tsx

feat: Heads up

---

src/App.tsx
src/views/LegalPages/PrivacyPolicy.tsx
src/views/LegalPages/TermsAndConditions.tsx
src/views/LegalPages/styles.tsx

For QA purposes add "/terms" and "/privacy" to the URL, as the links would only appear once the UI Kit is updated

chore: Legal pages

---

package.json
src/App.tsx
src/views/LegalPages/PrivacyPolicy.tsx
src/views/LegalPages/TermsAndConditions.tsx
src/views/LegalPages/styles.tsx
src/views/Swap/components/CurrencyInputHeader.tsx
yarn.lock

feat: Update uikit

---

src/App.tsx
src/views/LegalPages/TermsOfUse.tsx
src/views/LegalPages/styles.tsx

Feat legal pages

---

package.json
yarn.lock

feat: Autonomy increment

---

src/config/constants/jungleFarms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: GENV3 jungle farm

---

package.json
src/config/constants/jungleFarms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts
yarn.lock

Update Listing Info - GENV3 filename update

---

src/components/SwapBanner/index.tsx
src/views/Swap/index.tsx

https://www.loom.com/share/3b83da69a63c4506ad1fcd7a61c29ce0

feat: Rotating banners for swap page

---

package.json
yarn.lock

feat: Rotating banner

---

src/components/SearchModal/ImportToken.tsx
src/config/constants/ifo.ts
src/config/localization/translations.json
src/utils/getTokenUsdPrice.ts
src/views/Homepage/components/TrendingTokens/TrendingTokens.tsx
src/views/Homepage/components/WelcomeContent/WelcomeContent.tsx

Several Small Changes

---

src/components/Logo/CurrencyLogo.tsx

I've also removed the box shadow, as the effect seemed unnatural to me, let me know if you want me to restore it.
Old: 
New:

chore: Logo updates

---

src/views/Bills/hooks/getBillType.tsx
src/views/Bills/hooks/useBuyBill.tsx
src/views/Bills/hooks/useClaimAll.tsx
src/views/Bills/hooks/useClaimBill.tsx
src/views/Bills/hooks/useTransferBill.tsx

chore: Track jungle bills

---

src/components/Logo/CurrencyLogo.tsx
src/views/Bills/hooks/getBillType.tsx
src/views/Bills/hooks/useBuyBill.tsx
src/views/Bills/hooks/useClaimAll.tsx
src/views/Bills/hooks/useClaimBill.tsx
src/views/Bills/hooks/useTransferBill.tsx

joooongle bill anal(lytics)

---

src/config/constants/bills.ts
src/config/constants/types.ts
src/views/Bills/components/Menu/styles.ts
src/views/Bills/index.tsx

chore: Bills UI updates & z-index minor bugfix

---

src/components/Menu/chains/bscConfig.ts

fix: Adjust NEW tag

---

src/views/Vaults/Vaults.tsx
src/views/Vaults/components/DisplayVaults.tsx
src/views/Vaults/components/Menu/constants.ts

fix: Filtering vaults

---

src/config/constants/tokens.ts
src/config/constants/vaults.ts

feat: ETH and Ape Vaults

---

src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Homepage/components/Services/Services.tsx

fix: Correct output token on homepage

---

package.json

Update Listing Info - Listed TOR & HEC

---

src/config/constants/tokens.ts
src/config/constants/vaults.ts

feat: Dot and Avax vaults

---

package.json

feat: DOT & AVAX Vaults

---

src/config/constants/tokens.ts
src/config/constants/vaults.ts
yarn.lock

feat: Weekend vaults

---

src/config/constants/vaults.ts

feat: Sunday vaults

---

package.json

Updated Listing Info : Lico index & Delist BFT

---

src/config/constants/tokens.ts
src/config/constants/vaults.ts

feat: ADA max vaults

---

src/config/constants/tokens.ts
src/config/constants/vaults.ts

feat: Link and aave vaults

---

src/hooks/useSwapCallback.ts
src/utils/wallchainService.ts

fix: Allow bonus when not logged in

---

src/views/Dex/RemoveLiquidity/components/Actions/index.tsx
src/views/Dex/RemoveLiquidity/components/Actions/types.ts
src/views/Dex/RemoveLiquidity/components/PoolInfo/index.tsx
src/views/Dex/RemoveLiquidity/components/RemoveLiquidityModal/index.tsx
src/views/Dex/RemoveLiquidity/components/RemoveLiquidityModal/types.ts
src/views/Dex/RemoveLiquidity/index.tsx
src/views/Dex/Swap/index.tsx

fix: Big int issue and wrap

---

src/utils/getDotPos.ts
src/views/Homepage/components/News/News.tsx
src/views/Homepage/components/Services/Services.tsx
src/views/Homepage/components/Values/Values.tsx

fix: Carousel's dot length & position

---

src/views/Pools/components/Actions/HarvestAction.tsx

fix: Change to Ape Harder

---

package.json

feat: Token version

---

src/state/types.ts
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/Actions/types.ts
src/views/Bills/components/Modals/BuyBillModalView.tsx
src/views/Bills/hooks/useBuyBill.tsx

feat: Add bills price into google analytics

---

package.json
src/config/constants/bills.ts
src/hooks/useSwapCallback.ts
yarn.lock

chore: Increment package version

---

src/config/constants/bills.ts

chore: Enable DR bill

---

package.json

chore: Delist illiquid tokens

---

package.json
src/config/constants/bills.ts

Modal Updates

---

src/components/UnlockButton.tsx
src/config/constants/bills.ts
src/views/Bills/components/BillsListView.tsx
src/views/Vaults/components/DisplayVaults.tsx
yarn.lock

fix: Minor fixes

---

src/config/constants/jungleFarms.ts
src/config/constants/pools.ts
src/config/constants/tokens.ts

feat: PXP jungle farm

---

src/views/Bills/components/BillsListView.tsx

fix: Bills color

---

package.json

NUM token listing

---

src/views/JungleFarms/JungleFarms.tsx
yarn.lock

- /src/views/JungleFarms/JungleFarms.tsx (change isFinished settings for currJungleFarms)
**Explanation**:
The `currJungleFarms` seems to have been derived from the same code as the `curPools` in (/src/views/Pools/Pools.tsx), while we need to keep the pool with `sousId 0` which is a banana pool and will always be active, the jungle farms doesn't need to keep the jungle farm with Id 0 which in this case turned out to be the LC-Bnb farm.

LC-BNB Jungle Farm to Inactive on Finish

---

src/state/farms/hooks.ts
src/state/pools/hooks.ts
yarn.lock

fix: Pool and farm load times

---

src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts

fix: Trading title

---

src/views/AdminPools/AdminPools.tsx

fix: Add admin pools

---

package.json

feat: List MHUNT

---

src/components/ListView/styles.ts
src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts
src/components/RoiCalculator/CalcButton.tsx
src/components/RoiCalculator/CurrencyInput.tsx
src/components/RoiCalculator/DetailsContent.tsx
src/components/RoiCalculator/RoiCalculatorModal.tsx
src/components/RoiCalculator/styles.ts
src/components/RoiCalculator/tokenInfo.ts
src/config/localization/translations.json
src/state/farms/hooks.ts
src/state/pools/hooks.ts
src/utils/compoundApyHelpers.ts
src/views/AdminPools/AdminPools.tsx
src/views/DualFarms/components/DisplayFarms.tsx
src/views/Farms/components/DisplayFarms.tsx
src/views/Pools/components/DisplayPools.tsx
src/views/Vaults/components/DisplayVaults.tsx
yarn.lock

feat: Advanced calculator

---

src/components/SearchModal/ImportList.tsx
src/components/SearchModal/ImportToken.tsx
src/config/constants/lists.ts
src/views/Farms/constants.ts
src/views/Ifos/components/Ideology/Ideology.tsx
yarn.lock

Quick updates

---

package.json

List FLOKI

---

src/views/DualFarms/components/DisplayFarms.tsx

feat: Added liquidity modal for Polygon

---

package.json
src/components/TextInput/TextInput.tsx
src/components/TransactionConfirmationModal/index.tsx
src/components/UnlockButton.tsx
src/config/localization/translations.json
src/hooks/useAuth.ts
src/hooks/useSelectNetwork.ts
src/views/ApeZone/components/ConvertCard.tsx
src/views/Auction/components/Actions/SubmitBid.tsx
src/views/Bills/components/Actions/Approve.tsx
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/Actions/ClaimAll.tsx
src/views/Bills/components/Actions/Transfer.tsx
src/views/Dex/Swap/components/ConfirmSwapModal.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/Actions/CreatePresale.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/PairCreation/PairCreation.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/PresaleDetails/TokenInput.tsx
yarn.lock

fix: Lots of fixies for marketing

---

package.json

Updated Listing Info: Listed BAPE

---

src/components/GnanaModal/components/InputPanel.tsx
src/views/Dex/Swap/components/ConfirmSwapModal.tsx
src/views/NfaStaking/components/PoolCard/CardHeading.tsx

fix: Temp fix

---

src/state/hooks.ts
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/Actions/CreatePresale.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/PairCreation/PairCreation.tsx

fix: Ssiao tokens

---

src/views/Homepage/components/News/News.tsx

fix: Swap delay

---

package.json
src/App.tsx
src/views/Homepage/components/News/News.tsx
yarn.lock

Cleanup & Fixies

---

src/components/Blocklist/index.tsx

feat: Add dev api

---

src/components/MarketingModalCheck/MarketingModalCheck.tsx

chore: Fix default modal to only show on homepage

---

src/views/Stats/components/Analytics/components/TVLBreakdown/index.tsx

fix: Chart element

---

src/config/localization/translations.json
src/state/protocolDashboard/types.ts
src/views/ProtocolDashboard/Treasury/components/TreasuryBreakdown/AssetBreakdown/AssetCard.tsx
src/views/ProtocolDashboard/Treasury/components/TreasuryBreakdown/AssetBreakdown/styles.ts
src/views/ProtocolDashboard/Treasury/components/TreasuryBreakdown/index.tsx
src/views/ProtocolDashboard/Treasury/components/TreasuryHistory/index.tsx

fix: Dashboard changes v1

---

package.json

Updated Listing Info - Listing BRZ, BSR, RWX & Delistings

---

package.json

List TRAXX

---

src/config/constants/apezone.ts
src/config/constants/ifo.ts

chore: Update to 6 months

---

src/config/constants/apezone.ts
src/config/constants/ifo.ts

fix: Wording on IAO

---

src/components/Blocklist/index.tsx
yarn.lock

chore: Update

---

src/components/Blocklist/index.tsx

chore: Fix initial state

---

src/state/network/index.ts

chore: Ethereum direct link

---

package.json
src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts

CHRP Listing

---

src/hooks/Trades.ts
yarn.lock

Singlehop not multihop issue

---

src/components/DualAddLiquidity/components/ZapSwitch.tsx
src/views/Bills/components/Actions/styles.ts
src/views/DualFarms/components/DisplayFarms.tsx
src/views/Farms/components/DisplayFarms.tsx
src/views/JungleFarms/components/DisplayJungleFarms.tsx
src/views/Vaults/components/DisplayVaults.tsx

chore: Tooltip for zap modal

---

src/App.tsx
src/components/Menu/chains/bscConfig.ts
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Dex/Pool/index.tsx
vercel.json

Chore: Remove SS-IAOs and Bug Fixes

---

package.json

Updated Listing Info - Listed AXN

---

src/state/dualFarms/fetchDualFarmUser.ts
src/state/dualFarms/index.ts

fix: Dual farms data fetching

---

package.json

fix: Polygon Farm Updates

---

src/state/dualFarms/hooks.ts
src/state/dualFarms/index.ts

fix: Loading issues

---

src/state/dualFarms/index.ts
yarn.lock

fix: User data redux update

---

src/App.tsx
src/views/Dex/PoolFinder/index.tsx

chore: Fixed poolfinder and clean app.tsx

---

src/components/ServiceTokenDisplay/index.tsx
src/components/ServiceTokenDisplay/styles.ts

chore: Fix icons borders

---

src/components/MarketingModalCheck/MarketingModalCheck.tsx

fix: Comment our default logic

---

src/components/DualAddLiquidity/components/ZapSwitch.tsx
src/components/DualAddLiquidity/styles.ts
src/state/user/actions.ts
src/state/user/hooks/index.tsx
src/state/user/reducer.ts

chore: Fix slippage modal

---

src/views/Auction/components/NfaListingModal.tsx
yarn.lock

chore: Scrollable NFA modal

---

src/views/BabRaffle/components/NFBGiveaway.tsx

fix: Wording for clarity

---

src/views/Auction/Auction.tsx
src/views/Auction/components/Container.tsx
src/views/Auction/components/History.tsx

chore: Fix nfa page

---

src/views/Auction/Auction.tsx
src/views/Auction/components/AuctionCardVarients/HistoryCard.tsx
src/views/Auction/components/Container.tsx
src/views/Auction/components/History.tsx
src/views/BabRaffle/components/NFBGiveaway.tsx

Minor NFT Fixes

---

src/views/Auction/Auction.tsx
src/views/Auction/components/AuctionCardVarients/HistoryCard.tsx
src/views/Auction/components/Container.tsx
src/views/Auction/components/History.tsx
src/views/BabRaffle/components/NFBGiveaway.tsx

NFT Reversion

---

src/components/DualAddLiquidity/ZapLiquidity.tsx
src/hooks/useZapCallback.ts
src/views/Bills/components/Actions/Buy.tsx
src/views/Dex/Zap/index.tsx

chore: Update zap analytics

---

src/App.tsx
src/hooks/useCircularStaking.ts

fix: Hotfix for circular modals

---

package.json

chore: Revert cache clean command

---

src/views/Auction/Auction.tsx
src/views/Auction/components/AuctionCardVarients/HistoryCard.tsx
src/views/BabRaffle/components/NFBGiveaway.tsx

Circular Staking Fix

---

src/components/Blocklist/index.tsx

chore: Update blocklist

---

src/App.tsx
src/views/Homepage/components/Services/Services.tsx
src/views/Homepage/components/Services/styles.tsx

- Remove the HomePage component from lazy loading and display as is.

Fix Featured Products Section Bab Raffle Page

---

README.md
package.json

Discord Link Change

---

src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/UserBillViews/BillCard.tsx
src/views/ProtocolDashboard/Treasury/components/TreasuryBreakdown/AssetOverview/index.tsx
yarn.lock

fix: Minor resolutions

---

src/views/ProtocolDashboard/Treasury/components/TreasuryBreakdown/AssetOverview/index.tsx

fix: Protocol dashboard

---

package.json

Vanity link change

---

src/App.tsx
src/components/ServiceTokenDisplay/styles.ts
src/hooks/useSelectNetwork.ts
src/hooks/useStake.ts
src/views/Bills/components/Actions/Buy.tsx
src/views/JungleFarms/components/Actions/StakeActions.tsx

chore: Tracking fixes and upgrades

---

public/index.html

chore: Update metadata

---

src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts
src/components/Menu/chains/tlosConfig.ts
src/views/Dex/Migrate/index.tsx
src/views/NfaStaking/NfaStaking.tsx

feat: Cleanup & NFA Staking Notice

---

src/views/Bills/components/BillsListView.tsx
src/views/Homepage/components/Values/defaultValues.ts

chore: Bug fixes

---

package.json

3air Listing

---

package.json

sTLOS Listing

---

src/components/MarketingModalContent/Quests/slides/QuestSlide1.tsx
src/components/MarketingModalContent/Quests/slides/QuestSlide4.tsx

chore: Update wording on tutorial

---

src/views/Auction/components/Price.tsx

chore: Update broken price

---

package.json

chore: List AMT

---

src/components/Menu/index.tsx

fix: Sid condition

---

src/components/Menu/chains/bscConfig.ts
src/views/Nft/index.tsx

chore: Remove NFA Staking pool link

---

src/state/info/hooks.ts

Fix: Info page

---

src/config/constants/types.ts
src/state/dualFarms/cleanDualFarmData.ts
src/state/stats/getStats.ts
src/state/types.ts
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/BillsListView.tsx
src/views/Bills/components/Modals/TransferBillModal.tsx
src/views/Bills/components/Modals/UserBillModalView.tsx
src/views/Bills/components/UserBillViews/BillCard.tsx
src/views/Bills/components/UserBillViews/UserBillListView.tsx
src/views/Iazos/components/CreateIazo/components/CreateYourPresale/Actions/CreatePresale.tsx
src/views/JungleFarms/components/DisplayJungleFarms.tsx
src/views/Pools/components/DisplayPools.tsx
src/views/PoolsLegacy/components/ContainerDetail.tsx
src/views/PoolsLegacy/components/Detail.tsx

fix: Added chain specific decimals to all the decimals

---

package.json

MONSTA listing increment package json

---

src/utils/roundNumber.ts
src/views/Bills/components/BillsListView.tsx

Fix soldout bill

---

package.json

Fix for Oversold Bills

---

src/components/Blocklist/index.tsx

chore: Blocklist aBNBc hacker

---

src/components/ListViewMenu/styles.ts
src/views/Pools/components/Menu/styles.ts
src/views/Vaults/components/Menu/styles.ts

chore: Fix zindex issue

---

src/views/Dex/Migrate/MigrateAll/components/SuccessfulMigrationModal/index.tsx

chore: Update wording

---

src/views/Dex/Pool/index.tsx
src/views/Homepage/components/Services/Services.tsx

chore: Fixed positon bugs and Bills arrow

---

package.json

Incrementing lists version

---

src/views/PoolsLegacy/components/PoolTabButtons/index.tsx
yarn.lock

chore: Hot fix on admin pools

---

src/views/InfoPage/views/Token/index.tsx

chore: Updated token check

---

src/state/statsPage/api.ts
src/state/statsPage/mappings/chainMap.ts
src/state/statsPage/mappings/index.ts
src/state/statsPage/mappings/rawToNfts.ts
src/state/statsPage/mappings/rawToPortfolio.ts
src/state/statsPage/mappings/rawToProjected.ts
src/state/statsPage/mappings/rawToVested.ts
src/state/statsPage/types.ts
src/views/Stats/Stats.tsx
src/views/Stats/components/Analytics/components/AssetBreakdown/index.tsx
src/views/Stats/components/Analytics/components/ProjectedEarnings/index.tsx
src/views/Stats/components/Analytics/components/TVLBreakdown/index.tsx
src/views/Stats/components/Analytics/components/VestedEarnings/index.tsx
src/views/Stats/components/BannerStats/index.tsx
src/views/Stats/components/CardValue.tsx
src/views/Stats/components/ChainIcon.tsx
src/views/Stats/components/ChainLogo.tsx
src/views/Stats/components/NFT/components/BillCard.tsx
src/views/Stats/components/NFT/styles.ts
src/views/Stats/components/Portfolio/components/ProductCard/ProductCardHeader.tsx
src/views/Stats/components/Portfolio/components/ProductCard/ProductChainList.tsx
src/views/Stats/components/Portfolio/components/ProductCard/index.tsx
src/views/Stats/components/Portfolio/index.tsx

- Add Telos Chain to Stats Page
- Overall improvements in code readability and some reuse of components.
- Disable white spaces to review the code.

[FEAT]: Telos chain

---

src/views/Auction/Auction.tsx
src/views/Auction/components/Actions/ListYourNfa.tsx
src/views/Auction/components/AuctionCardVarients/LiveCard.tsx
src/views/Auction/components/History.tsx
src/views/Auction/components/Positions.tsx
src/views/Auction/styles.ts
yarn.lock

chore: Fix nfa view

---

package.json

Increment apeswap-lists version

---

src/views/Bills/components/BillsListView/index.tsx

chore: Hide 100% discount bills

---

src/views/Bills/components/BillsListView/components/BillsRows.tsx

chore: Fixed soldout bills view

---

README.md
package.json
src/hooks/useTokenPriceUsd.ts
src/state/tokenPrices/fetchPrices.ts
yarn.lock

chore: Fixed pricegetter to always use 18 decimals

---

README.md
package.json
src/hooks/useTokenPriceUsd.ts
src/state/tokenPrices/fetchPrices.ts
src/views/Bills/components/Actions/Buy.tsx
src/views/Bills/components/BillsListView/components/BillsRows.tsx
src/views/Bills/components/BillsListView/index.tsx
yarn.lock

chore: List TRIVIA & Bills Cleanup

---

package.json

Increment to Support Fruit Farm & Pool

---

package.json

Increment package versions

---

package.json

Increment lists version

---

src/state/statsPage/mappings/rawToPortfolio.ts
src/views/Stats/components/Portfolio/index.tsx

- Filter products without earnings or value before rendering since TB or IAOs can be still displayed even when fully vested.

refactor: Portfolio Balances

---

src/components/Tooltip/JungleFarmsEndsIn.tsx
src/components/Tooltip/PoolsEndsIn.tsx
src/components/Tooltip/Tooltip.tsx
src/views/Pools/components/DisplayPools.tsx

chore: Added pools remaining time

---

src/components/MarketingModalContent/Tutorial.tsx
src/components/MarketingModalContent/TutorialSlides.tsx
src/components/Tooltip/JungleFarmsEndsIn.tsx
src/components/Tooltip/PoolsEndsIn.tsx

Connect wallet Fix

---

src/App.tsx

chore: Render floating docs after menu

---

src/views/MigrateMasterApeV2/components/Steps/ApproveStake.tsx

chore: Remove toggle

---

package.json

LIQ Bill Listing

---

src/state/masterApeMigration/hooks.ts
src/state/masterApeMigration/updater.tsx
yarn.lock

fix: Analytic bugs

---

package.json
src/state/masterApeMigration/hooks.ts
src/state/masterApeMigration/updater.tsx
yarn.lock

fix: Analytics

---

src/views/Vaults/LegacyVaults.tsx

fix: Filter add vaults with dust

---

src/App.tsx
src/components/MigrationRequiredPopup/index.tsx
src/state/masterApeMigration/hooks.ts
src/views/Farms/FarmsV2.tsx
src/views/MigrateMasterApeV2/index.tsx
src/views/Pools/Pools.tsx
src/views/Vaults/VaultsV3.tsx

fix: Reduce calls on load

---

src/views/Vaults/components/DisplayVaults.tsx

chore: Change max to auto

---

package.json
yarn.lock

chore: Update bills

---

package.json
src/state/lpPrices/hooks.ts
src/state/tokenPrices/fetchPrices.ts
src/views/Farms/FarmsV2.tsx
src/views/Pools/Pools.tsx
src/views/Vaults/VaultsV3.tsx
yarn.lock

fix: Update innactive search and innactive pools

---

package.json
src/state/lpPrices/hooks.ts
src/state/tokenPrices/fetchPrices.ts
src/views/Farms/FarmsV2.tsx
src/views/Pools/Pools.tsx
src/views/Vaults/VaultsV3.tsx
yarn.lock

Chore: Inactive & Farm APR

---

package.json
src/components/MigrationRequiredPopup/index.tsx

chore: Changed text-updated pckg

---

package.json
src/state/masterApeMigration/reducer.ts
src/state/masterApeMigration/utils.ts
src/state/vaultsV3/fetchVaultsV3User.ts
src/state/vaultsV3/index.ts
src/views/MigrateMasterApeV2/hooks/useStakeAll.ts
src/views/MigrateMasterApeV2/hooks/useStakeApproveAll.ts
src/views/Vaults/VaultsV3.tsx
src/views/Vaults/components/DisplayDepsoitVaultsV2.tsx
src/views/Vaults/components/DisplayVaults.tsx
src/views/Vaults/components/MigrateActionsButtons/Stake.tsx
yarn.lock

fix: Add auto vault and remove max

---

package.json
src/state/info/hooks.ts
yarn.lock

Increment lists and tokenlists repos

---

package.json

AVANA Changes

---

package.json

Wrapped Coinflect Changes

---

package.json

chore: AVAN Bill

---

src/state/bills/fetchBillsUser.ts
src/utils/multicall.ts
yarn.lock

chore: Batch multicall

---

package.json
src/state/bills/fetchBillsUser.ts
src/utils/multicall.ts
yarn.lock

fix: Batch Bills Multicall

---

package.json
yarn.lock

chore: Add ZBC farm

---

package.json

WCFLT Bill

---

package.json
src/config/abi/bill.json
src/hooks/api.ts
src/state/bills/fetchBills.ts
src/state/bills/fetchBillsCalls.ts
src/state/bills/fetchBillsUser.ts
src/utils/multicall.ts
src/views/Bills/components/Actions/Buy.tsx
yarn.lock

feat: Add v2 bill

---

package.json
yarn.lock

chore: Jungle farm

---

package.json
yarn.lock

XTAL Jungle Farm

---

package.json

Increment lists repo

---

package.json

TRIVIA Bill Addition

---

package.json

Stader JF Update

---

package.json

Incrementing token-lists pckg

---

README.md
package.json

Increment lists PR

---

package.json
yarn.lock

Adding Chain Guardians Bill & Listing

---

src/state/bills/fetchBillsUser.ts
yarn.lock

chore: Batch

---

package.json

feat: Telos Bill

---

src/views/ApeZone/components/GnanaDisclaimers/GnanaDisclaimers.tsx

chore: Update GNANA disclaimer

---

src/state/info/queries.ts

fix: Updated graphs to accept polygon error

---

src/config/constants/chains.ts

fix: Removed Telos graph while waiting on fix

---

package.json
src/views/ApeZone/components/GnanaDisclaimers/GnanaDisclaimers.tsx

Increment lists pckg version

---

src/config/constants/chains.ts
src/state/info/hooks.ts
src/state/info/index.ts

chore: Telos farms and bills fix

---

package.json

chore: Increment list and token-list repos

---

package.json

chore: Increment lists and token lists versions

---

package.json

Increment List for New Bill

---

package.json

chore: Increment lists/tokenlists repos

---

package.json

Increment lists and tokenlists versions

---

package.json
src/config/constants/chains.ts
src/views/InfoPage/components/Chart/ChartItem.tsx
src/views/InfoPage/components/Chart/index.tsx
src/views/InfoPage/components/Modals/LegacySelectModal.tsx
src/views/InfoPage/components/NetworkSelector/index.tsx
src/views/InfoPage/components/TrendingTokens/TrendingTokens.tsx
src/views/InfoPage/components/styles.ts
src/views/InfoPage/views/Token/index.tsx

feat: Added Arbitrum data to info page

---

package.json

Telos JF Updates

---

package.json

Increment token-lists version

---

package.json
src/config/constants/chains.ts

chore: Increment token-lists version

---

package.json
yarn.lock

chore: Increment to disable vaults

---

package.json
src/views/InfoPage/components/styles.ts
yarn.lock

Limit Orders Bump

---

package.json

ORBS listing

---

package.json

rASKO logo update

---

src/views/Dex/components/DexNav/index.tsx

feat: Add v3 toggle

---

src/views/InfoPage/components/Modals/V3SelectModal.tsx
src/views/InfoPage/components/NetworkSelector/index.tsx

fix: Add v3 links

---

package.json

V3 Info Page Addition

---

src/views/Homepage/components/WelcomeContent/WelcomeContent.tsx
src/views/Homepage/components/WelcomeContent/slides/ApeSwapV3.tsx
yarn.lock

chore: Update homepage to handle V3 component

---

package.json
src/views/Homepage/components/WelcomeContent/WelcomeContent.tsx
src/views/Homepage/components/WelcomeContent/slides/ApeSwapV3.tsx
yarn.lock

chore: V3 Homepage & Autonomy Package

---

package.json
src/state/statsPage/api.ts
src/views/Homepage/components/WelcomeContent/WelcomeContent.tsx
src/views/Homepage/components/WelcomeContent/slides/ApeSwapV3.tsx
src/views/Homepage/components/WelcomeContent/slides/styles.ts
src/views/Homepage/components/WelcomeContent/styles.tsx
yarn.lock

Arbitrum ApeStats Integration 💙

---

src/components/Menu/GlobalSettings/SettingsModal.tsx
src/components/SquidBridge/SquidBridge.tsx
src/views/Dex/components/DexNav/index.tsx
src/views/Dex/components/DexNav/styles.ts
yarn.lock

Squid bridge

---

package.json

chore: Increment token-lists PR

---

package.json

Telos Farm Disactivate

---

package.json

chore: Increment list and tokenlists versions

---

package.json

Increment token-lists repo

---

package.json

chore: Increment token-lists/lists versions

---

src/views/Dex/Swap/components/Risk/Risk.tsx

chore: Risk scanner change

---

src/components/ServiceTokenDisplay/index.tsx
src/views/Bills/components/BillsListView/components/BillsRows.tsx
src/views/Bills/components/BillsListView/index.tsx
src/views/Bills/components/Modals/BuyBillModalView.tsx
yarn.lock

chore: Bond design changes

---

package.json

Update lists version

---

package.json
src/components/Tooltip/Tooltip.tsx
src/views/Bills/components/BillsListView/components/BillsRows.tsx
yarn.lock

chore: Bond insights addition

---

package.json
yarn.lock

`@ape.swap/apeswap-lists@1.2.2`

Deprecate Old GNANA->BANANA Pool

---

package.json
src/components/Menu/chains/arbitrumConfig.ts
src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts
src/components/Menu/chains/tlosConfig.ts
src/views/Dex/components/DexNav/index.tsx

Final Changes for UI Swap

---

src/views/Dex/components/DexNav/index.tsx

chore: Remove unnecesary env variable

---

package.json
src/components/FloatingDocs/index.tsx

Add ApeSwapNFT Bond

---

README.md

chore: Force deploy

---

.github/workflows/test.yml

Can you check? I hope it was a working script.

fix: test.yml

---

src/components/Menu/chains/arbitrumConfig.ts
src/components/Menu/chains/bscConfig.ts
src/components/Menu/chains/ethConfig.ts
src/components/Menu/chains/maticConfig.ts
src/config/constants/chains.ts
src/config/constants/networks.ts

Nav Bar & Nodes

---

package.json
yarn.lock

-Incremented lists version to update finished data of some products.

chore: Increment lists version

---

package.json

Relisting SWT
